# GitHub Pages configuration
title: Agentic AI Development
description: Documentation and scaffolding for agentic AI development

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Collections
collections:
  scaffolding:
    output: true
    permalink: /:collection/:name/
  best-practices:
    output: true
    permalink: /:collection/:name/

# Navigation
defaults:
  - scope:
      path: ""
      type: "scaffolding"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "best-practices"
    values:
      layout: "default"

# Minima theme settings
minima:
  skin: auto
  social_links: []

# Hide footer
show_excerpts: false